@startuml

class User
class Role
class Permission
class View
class Database
class Table
class Schema
class Trigger
class Attribute
class Constraint
class Key
class Foreign
class Primary

' ==== Relaciones ====
User -- Role : has a
Role -- Permission : has
Permission ..> View : over a
View ..> Table : depends on
Database *-- Table : contains
Table ..> Schema : needs
Table o-- Trigger : could have
Table *-- Attribute : has
Table *-- Key : has
Attribute o-- Constraint : could have
Key <|-- Primary : inherits
Key <|-- Foreign : inherits

@enduml